<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\ConfederationCountryListHandler::class => App\Handler\ConfederationCountryListHandlerFactory::class,
            App\Handler\ConfederationListHandler::class => App\Handler\ConfederationListHandlerFactory::class,
            App\Handler\CountryListHandler::class => App\Handler\CountryListHandlerFactory::class,
            App\Handler\CountryTeamListHandler::class => App\Handler\CountryTeamListHandlerFactory::class,
            App\Handler\TeamCreateHandler::class => App\Handler\TeamCreateHandlerFactory::class,
            App\Handler\TeamDeleteHandler::class => App\Handler\TeamDeleteHandlerFactory::class,
            App\Handler\TeamGetHandler::class => App\Handler\TeamGetHandlerFactory::class,
            App\Handler\TeamListHandler::class => App\Handler\TeamListHandlerFactory::class,
            App\Handler\TeamUpdateHandler::class => App\Handler\TeamUpdateHandlerFactory::class,
        ],
    ],
];
